#
#---- BASE NODE -----
#this uses alpine as the base and installs requirements to ensure a smaller container
FROM node:12-alpine AS base
RUN apk update &&  apk add --no-cache --update nodejs nodejs-npm tini
WORKDIR /root/app
ENTRYPOINT ["/sbin/tini", "--"]
COPY package.json .
COPY nginx.conf .
COPY README.md .
COPY src src


#--- dependencies ----
#this will install all dependencies and prod dependencies for later consumption
FROM base AS dependencies
RUN npm install
RUN npm run build-storybook

#---- test install ----
# run tests here
#---- release ----
FROM nginx:1.15
COPY --from=dependencies /root/app/storybook-static/ /usr/share/nginx/html
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY --from=dependencies /root/app/nginx.conf /etc/nginx/conf.d/default.conf